### PR TITLE
Support sharded database environment

### PR DESCRIPTION
**Pull request by jkdufair**
These commits support the use use of a 1:1 redis<->db mapping. It does so by passing the `DbConnection` through the various interception methods as a parameter, allowing a potential `ICache` instance to examine the `DbConnection` instance to maintain said mapping.

See https://github.com/purdue-tlt/EFCache.Sharding for an implementation of a sharded cache.

### CODE REVIEW

**Comment by moozzyk** [comment]
I am sorry, but this does not fit here. I believe it should be possible to implement this functionality externally - i.e. without changes to main interfaces. 
Another reason to not take this change is that it breaks current implementations of the `ICache` implementations because of the changes to the `ICache` interface. Note that the default parameters are not supplied automatically by the callee but are compiled into the caller, hence existing implementation will not work without re-compiling.
This change also updates the lowest supported version of the .NET Framework as well as the lowest supported version of EF - changes I don't want to make.
In general (for any bigger contribution to any open source project) I would recommend starting a thread to agree with maintainers on the change and the scope before opening a PR - it might save your time and give you clarity on the kind of changes that could be accepted. 
If you need your changes in your own project, feel free to fork this project and use your changes but I am not going to take your pull request, sorry.
I still want to thank you for the interest in this project and your attempt to improve it. I do appreciate it!

**Comment by jkdufair** [comment]
Thanks for taking a look. We love your project and we needed these changes for our system. Thought we'd offer them back upstream.

Indeed, I had hoped to do it without changing the interface, but it doesn't appear to be possible due to the nature of how interception seems to work in EF.

If you are aware of a way to do so and you'd otherwise be interested in having a PR, let me know. We can lower the .NET and EF requirements no problem.

**Comment by moozzyk** [comment]
I am not quite sure why you can't implement the `ICache` interface as it is now and just take the connection (or a callback to a connection factory/provider) in the ctor of your `ICache` implementation. This is how it is implemented in the [EFCache.Redis](https://www.nuget.org/packages/EFCache.Redis/) - an implementation of the `ICache` interface which uses Redis to cache items instead of keeping them as a dictionary in memory which is what InMemoryCache does.

**Comment by jkdufair** [comment]
Hi Pawel -

I did some digging on this. I'm actually already using EFCache.Redis as well. My application has a DbConnectionFactory that instantiates a `DbConnection` based on a given shard name. I have a Dictionary that maintains a mapping between each shard's `DbConnection` and an instance of `RedisCache`.

I tried finding a way to get a reference to the current instance of `DbConnection` at interception/DbCommand time and passing that to the constructor of my implementation of `ICache`. Alas, I do not believe it is possible to get that reference nor to create a callback as I don't believe there is anything that would call said callback!

I do believe I can accomplish what I need without modifying, `ICache`. But this would require me to subclass several of the EFCache classes that are declared as internal (i.e. CachingCommand). Would this be something you would consider? The idea is that I would create a subclass of `CacheTransactionHandler` and a subclass of `CachingCommand`.  `CachingCommand` has access to a `DbConnection`. This would allow me to call methods on my subclass of `CacheTransactionHandler` and pass the `DbConnection` through so it can then be used by my `ICache` implementation to dispatch the request to the right instance of `RedisCache`

Let me know if you'd be willing to accept a PR that changes the visibility of `CachingCommand` (and its dependencies) to `protected`.

Or if you have any other ideas for how I can get access to a DbConnection at interception time, I'd be open to them.

Thanks again for your consideration,
Jason Dufair

**Comment by jkdufair** [comment]
Hi again - I did even more digging and came up with a solution that works but is hacky. And involves an in memory cache of command definitions and string matching on the keys that are delivered to `CacheTransactionHandler`. I got stopped because even this solution won't work for `InvalidateSets`.

The fundamental problem is that `ICache` is normally instantiated at startup and is a singleton held on to by the `TransactionHandler`. When a `CachingCommand` is created, the wrapped `DbCommand` could be targeted to any `DbConnection` but there is no way for the the `TransactionHandler` and its single `ICache` instance to know with only a key (and in the case of `InvalidateSets` not even a key) which database is being targeted. The underlying assumption seems to be baked into EFCache that there will be one and only one cache. I tried developing some sort of `ICacheFactory` but this ended up being a dead end too.  

Would you be interested in working with me to remove this constraint? I can just keep my fork (and the fork I have for EFCache.Redis) but I believe the community would be better served if we offer a more comprehensive solution. One possibility could indeed be via my comment above where I have a separate repo but I can inherit from some of EFCache's classes maybe. Another solution is to extend EFCache to handle multiple `DbConnection`s and multiple `ICache`s 

Again, thanks for your consideration.

**Comment by jkdufair** [comment]
This is my PR for EFCache.Redis too. Sorry I didn't point to it right off the bat.
https://github.com/silentbobbert/EFCache.Redis/pull/36

**Comment by moozzyk** [comment]
> My application has a DbConnectionFactory that instantiates a DbConnection based on a given shard name. I have a Dictionary that maintains a mapping between each shard's DbConnection and an instance of RedisCache.

Each method of the `CacheTransactionHandler` that deals with caching takes `DbTransaction`. Could you use [`DbTransaction.DbConnection`](https://msdn.microsoft.com/en-us/library/system.data.common.dbtransaction.dbconnection(v=vs.110).aspx) property to get the cache instance you need to work with? I am wondering if you can just create your own transaction handler derived from the `CacheTransactionHandler` and overwrite all the methods that use `_cache.` to first resolve the cache instance you need to work with before invoking a cache related operation. I do acknowledge that the `CacheTransactionHandler` is not really designed well for subclassing (e.g. in your case you would have to provide a dummy `ICache` instance in the ctor, and would likely have to implement/copy all the methods that deal with caching) but if this approach works I think this can be fixed. 

With regards to other changes - at this point I don't think I would take any major/dramatic/risky changes/refactoring to the core code in general. The reason is that I am afraid of introducing regressions which will break people and which I won't be able to fix in timely manner given my other commitments.  

My feeling about your particular case is that the changes you would like to introduce are too specific to your use case (this is the first request to support shards and I don't know if this is because people don't need it or they had different requirements and were able implement it without changes to EFCache). EFCache is a general purpose extension and it tries to address the most common scenarios/needs. The flip side is that more advanced or rare scenarios can be hard (or impossible) to achieve.

**Comment by jkdufair** [comment]
Hi Pawel - I did play around with creating my own `CacheTransactionHandler` and I do think that will be a good approach. In order to avoid duplicating a fair bit of code that I would need to reference in my subclass that is declared `internal`, I'd need to make a PR that removes `internal` from a few classes. Would you be ok with that?

**Comment by jkdufair** [comment]
This is what I ended up doing:
https://github.com/purdue-tlt/EFCache/pull/1/commits/c20cc2bfc9821623a825bef37175fd046b51103b

In order to support:
https://github.com/purdue-tlt/EFCache.Sharding/tree/feature/sharded-cache-refactor

I had done basically what you did in your prototype, but ended up also needing to change visibility on a few other classes to support the `CacheTransactionHandler` and `CachingCommand` subclasses. Let me know if you think this is a reasonable solution and thanks for the time you've put into this.

**Comment by jkdufair** [comment]
Ok sorry. I misunderstood. I was under the impression you objected to changing `CacheTransactionHandler.GetItem()` and friends. The prototype is exactly what I needed. If you are willing to put that into EFCache, I can definitely use it.

Thanks so much for your help!

**Comment by moozzyk** [comment]
I did not want to change `CacheTransactionHandler` indeed but after I played with the code a little bit I remembered that the transaction can be null sometimes and therefore it is not always possible to extract a `DbConnection` from the `DbTransaction`. I think this is actually the cleanest way of enabling cache resolution and changes are pretty small. This can be considered a breaking change but in reality (as you have experienced) the `CacheTransactionHandler` was not extensible at all so I don't think anyone will be broken by this. The existing API surface did not change as well so existing apps should continue to work without any changes. I will add some test cases for the new scenarios and will put it on NuGet in the next few weeks.

**Comment by moozzyk** [comment]
FYI, I just published [EFCache 1.1.3](https://www.nuget.org/packages/EntityFramework.Cache/1.1.3) which contains changes you are after.

**Comment by jkdufair** [comment]
Again, many thanks for your work on this!

**Pull request closed without merging**
