### PR TITLE
Added InMemoryCache.ExpireAll() method

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by moozzyk** [comment]
What is the scenario for this? `Purge` already remove expired items. If you have lots of unexpired items that either means that they are being actually used frequently (in which case these items shouldn't be removed) or the timeouts/caching criteria in CachinPolicy are not set correctly.

Also, if this is needed, I think a better way of doing this would be to have a bool `removeUnexpiredItems` flag (set by default to false) on the `Purge` method instead of adding a new method.

**Comment by icnocop** [comment]
Hi.

Thank you for EFCache.

I'm currently using this new method in my integration tests.

For example, in `TestInitialize`, I delete and re-create the database and insert "seed" data. Some of the data is inserted into data tables which are part of the cache. So I have to clear the cache in order for the integration tests to pick up the new data.
Also, some integration tests change that data that was seeded, so I have to clear the cache so subsequent integration tests don't pick up the old data from a previous test.

I hope that makes sense.

I've updated the pull request with your recommendations.

Thank you!

**Comment by moozzyk** [comment]
Thanks a lot!

**Comment by moozzyk** [comment]
I just uploaded a new version (1.1.2) of the library that has your change to NuGet.

**Pull request merged**
